apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None
  selector:
    app: redis-master
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-master
spec:
  serviceName: redis-master
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
        sentinel: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-master
        image: redis:3.2.8
        imagePullPolicy: Always
        command: [ "redis-server", "/etc/redis/master.conf" ]
        ports:
        - containerPort: 6379
          name: redis-master
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: data
          mountPath: /data
      - name: redis-sentinel
        image: redis:3.2.8
        imagePullPolicy: Always
        ports:
        - containerPort: 26379
          name: redis-sentinel
        command: [ "redis-sentinel", "/etc/redis/sentinel.conf" ]
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
      volumes:
        - name: redis-config
          configMap:
            name: redis
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
